version: "3"
services:
  api_express:
    build: .
    container_name: node_express_api_container
    image: node_express_api_image
    command: yarn dev
    ports:
      - 3001:3001
    environment:
      - DATABASE_DEV_URL=${DATABASE_DEV_URL}
    volumes:
      - /usr/app/node_modules
      - ./src:/usr/app/src
      - ./build:/usr/app/build
    depends_on:
      - database

  database:
    container_name: postgres_database_container
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
